# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uta < Formula
  desc "CLI agent orchestrator — decompose goals, fan out to Claude Code / Gemini CLI, synthesize."
  homepage "https://unleashtheagents.ai"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.8.0/uta_0.8.0_darwin_amd64.tar.gz"
      sha256 "1e133178b98a006684c42aa1eaa9bae91c7201a9855ab39d04c73440b254fb21"

      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.8.0/uta_0.8.0_darwin_arm64.tar.gz"
      sha256 "660c6a5a319b783545c7d3c96dfc83b15381495e75fed55835d6866a2fec1356"

      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.8.0/uta_0.8.0_linux_amd64.tar.gz"
      sha256 "0f01d94e81a7e97863fa0683211a839d862f9fee44f0334987a7aa7e65a3659d"
      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.8.0/uta_0.8.0_linux_arm64.tar.gz"
      sha256 "ed5b8e08b6903782285a3307244eb6f5e867858d8e8cc13d8b88a16abfa1ba6b"
      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
  end

  test do
    system "#{bin}/uta", "--version"
  end
end
