# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uta < Formula
  desc "CLI agent orchestrator — decompose goals, fan out to Claude Code / Gemini CLI, synthesize."
  homepage "https://unleashtheagents.ai"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.7.0/uta_0.7.0_darwin_amd64.tar.gz"
      sha256 "63d003eed3d989855370f74ef07c907b23e847e0a09180f96e648314b234b80d"

      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.7.0/uta_0.7.0_darwin_arm64.tar.gz"
      sha256 "916d9cce3aefec9c33bb21ae9090b47f8bc36eba2037f118cb086bcd60afd38e"

      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.7.0/uta_0.7.0_linux_amd64.tar.gz"
      sha256 "9bc96dc705908ff50d99d9d30c808b65e9e93509f18a151dcb0bc60c94ccda6e"
      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.7.0/uta_0.7.0_linux_arm64.tar.gz"
      sha256 "e3a469ac1d146d3c5fe3f6461450c5799ac19bd1c5e7681e9b13d4f472a6233c"
      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
  end

  test do
    system "#{bin}/uta", "--version"
  end
end
