# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uta < Formula
  desc "CLI agent orchestrator — decompose goals, fan out to Claude Code / Gemini CLI, synthesize."
  homepage "https://unleashtheagents.ai"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.5.0/uta_0.5.0_darwin_amd64.tar.gz"
      sha256 "2a89b05889d3f54edd7b12477bdf90b3cede64c4e62474f496ebb9a60266c0e5"

      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.5.0/uta_0.5.0_darwin_arm64.tar.gz"
      sha256 "e210c4fce33dd4fd814729a56a15db7832073d2a9c9e9bc1e527f4454c07a2c5"

      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.5.0/uta_0.5.0_linux_amd64.tar.gz"
      sha256 "b9ac132568467496092ae7d7dfb1401b64492444c7f2a4130908ebe50964d794"
      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unleashtheagents/uta/releases/download/v0.5.0/uta_0.5.0_linux_arm64.tar.gz"
      sha256 "48053a60e04c4a174b64f58e678858d3806341258e421829e4a7ca451b0e85db"
      define_method(:install) do
        bin.install "uta"
        generate_completions_from_executable(bin/"uta", "completion")
      end
    end
  end

  test do
    system "#{bin}/uta", "--version"
  end
end
